convert_to <- list(logical = function(x) .Call(Clogical_to_bytes, x),
                   integer = function(x) .Call(Cint_to_bytes, x),
                   double = function(x) .Call(Cdouble_to_bytes, x),
                   complex = function(x) .Call(Ccomplex_to_bytes, x))
convert_from <- list(logical = function(x) .Call(Cbytes_to_logical, x),
                     integer = function(x) .Call(Cbytes_to_int, x),
                     double = function(x) .Call(Cbytes_to_double, x),
                     complex = function(x) .Call(Cbytes_to_complex, x))
create <- list(logical = logical,
               integer = integer,
               double = double,
               complex = complex)
